# ================================================
# 1. Fluent-Bit 서비스 전역 행동 설정 : 수집 -> 적재
# ================================================
[SERVICE]
    Flush       1       # 수집된 데이터를 전송하는 간격 설정. 1초
    Log_Level   info    # 일반 실행정보 및 디버그까지 출력받기. 
                        # Fluent-Bit 로그 레벨(error, warn, info, debug)
    
# ================================================
# 2. 데이터 수집 Input : sensor_json.log
# ================================================
[INPUT]
    Name        tail                                        # 파일의 끝에서 읽어온다. Plugin
    Path        /opt/airflow/sensor_logs/sensor_json.log    # 읽어올 로그 파일 경로
    Tag         sensor_json                                 # 데이터에 tag 표시. Output에서 태그를 보고 어디로 전송할지 필터링
    Parser      json                                        # 파일 내용 인식에 json parser를 사용

# ================================================
# 3. 데이터 수집 Input : sensor_text.log
# ================================================
[INPUT]
    Name        tail
    Path        /opt/airflow/sensor_logs/sensor_text.log
    Tag         sensor_text   

# ================================================
# 4. 데이터 배포 Output : kafka
# ================================================
[OUTPUT]
    Name        kafka
    Match       sensor_json
    Brokers     kafka:9092
    Topics      factory-json-topic
    Format      json
    
    

# ================================================
# 5. 데이터 배포 Output : Logstash (HTTP 전송)
# ================================================
[OUTPUT]

