# ================================================
# 1. Fluent-Bit 서비스 전역 행동 설정 : 수집 -> 적재
# ================================================
[SERVICE]
    # 수집된 데이터를 전송하는 간격 설정. 1초
    Flush       1
    # 일반 실행정보 및 디버그까지 출력받기.
    # Fluent-Bit 로그 레벨(error, warn, info, debug)
    Log_Level   info     


# ================================================
# 2. 데이터 수집 Input : sensor_json.log
# ================================================
[INPUT]
    # 파일의 끝에서 읽어온다. Plugin
    Name        tail
    # 읽어올 로그 파일 경로                     
    Path        /opt/airflow/sensor_logs/sensor_json.log 
    # 데이터에 tag 표시. Output에서 태그를 보고 어디로 전송할지 필터링 
    Tag         sensor.json        
    # 파일 내용 인식에 json parser를 사용         
    Parser      json                                        

# ================================================
# 3. 데이터 수집 Input : sensor_text.log
# ================================================
[INPUT]
    Name        tail
    Path        /opt/airflow/sensor_logs/sensor_text.log
    Tag         sensor.text   

# ================================================
# 4. 데이터 배포 Output : kafka
# ================================================
[OUTPUT]
    Name        kafka
    Match       sensor.json
    Brokers     kafka:9092
    Topics      factory-json-topic
    Format      json

# ================================================
# 5. 데이터 배포 Output : Logstash (HTTP 전송)
# ================================================
[OUTPUT]
    Name        http
    Match       sensor.text
    Host        logstash 
    Port        5044
    URI         /
    Format      json

    
    



