input {
    http {
        port => 5044
    }
}

filter {
    # 메세지에서 "ID=" 표현이 포함되는 경우만 파싱 : 보험
    # grok : 비정형 텍스트를 구조화된 (반정형)데이터로 바꾸는 도구
    # 정규표현식 패턴 활용 : 키-값으로 매핑 |   %{패턴명:필드명:데이터타입}
    if [message] =~ "ID=" {
        grok {
            match => { "message" => "\[%{TIMESTAMP_ISO8601:log_time}\] ID=%{DATA:device_id} \|     TEMP:%{NUMBER:temp:float} \|   HUMI:%{NUMBER:humi:float} \|    STAT:%{WORD:status}" }
        }
    }

}

output {
    kafka {
        bootstrap-servers   => "kafka:9092"
        topic_id            => "factory-text-topic"
        codec               => json
    }
    # 확인용 콘솔 출력 로그
    stdout {
        codec => rubydebug
    }
}